### PR TITLE
downgrade flink-table v0.10.1  to v0.10.0

### PR DESCRIPTION
**Pull request by zavalit**
building an exercises is just not possible, cause there is no  flink-table of version 0.10.1

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the PR. 
However, `flink-table` was included in the 0.10.1 release of Flink: https://maven-repository.com/artifact/org.apache.flink/flink-table/0.10.1
Could you please check again?

**Comment by zavalit** [comment]
hi Fabian, thx for the fast feedback.
may be i don't understand smth. but the defined resource ```http://repo1.maven.org/maven2/org/apache/flink/flink-table/0.10.1``` responses with 404

in opposite to ```http://repo1.maven.org/maven2/org/apache/flink/flink-table/0.10.0/``` that ships all it should to ship.

**Comment by rmetzger** [comment]
From here I could download the jar: http://search.maven.org/#artifactdetails%7Corg.apache.flink%7Cflink-table%7C0.10.1%7Cjar 
maybe the mirror is out of sync?

**Comment by zavalit** [comment]
definitely looks like that. cause the linked title there:
**"Browse Central For org.apache.flink : flink-table : 0.10.1"**
also leads to 404 page

**Comment by zavalit** [comment]
mirror got in sync, it seems to pull flink-table v0.10.1 also

**Comment by fhueske** [comment]
Nice, thanks for reporting back!

**Pull request closed without merging**
